### ISSUE TITLE
routes.rbでrootはどこに書くのが最適か？

### ISSUE THREAD

**Issue by popmac** [camp17-extra/activities#30]

**Comment by bake0937** [comment]
え？最初の方に書くんじゃないのかな

**Comment by popmac** [comment]
- CRUDアプリ
  - 上から2行目
- 映画レビューアプリ
  - 一番下
- プロフィールサービス
  - 上から3行目
- Railsチュートリアル
  - 一番上
- 実践Ruby on Rails4
  - 一番上
- 基礎Ruby on Rails
  - 一番上
- Ruby on Rails 5 アプリケーションプログラミング
  - 一番下
- パーフェクトRuby on Rails
  - 一番上

って感じだったので、どれが最適なんだってなってました(ﾟoﾟ;;

某教材でroutes.rbは上から順に読まれていくから、rootを書く場所によってはまずい(ざっくり)という記述を見かけた記憶があるんですが...

**Comment by popmac** [comment]
まとめると以下のような感じです

## 一番上
- Railsチュートリアル
- 実践Ruby on Rails4
- 基礎Ruby on Rails
- パーフェクトRuby on Rails

## 上から2行目
- CRUDアプリ

## 上から3行目
- プロフィールサービス

## 一番下
- 映画レビューアプリ
- Ruby on Rails 5 アプリケーションプログラミング

**Comment by KoichiOzaki** [comment]
rootは一番上に書いときゃいいと思います。
（もし、それ以外に優先して表示したいページとかがあれば別！）
ルーティングの注意点としては
上から探してマッチしたものに飛んで行くのでもし２つ以上マッチするものがあった場合には先にマッチしたものへ飛んでいくはずです。なので`:id`とかワイルドカード使ってるときに意図せず起きやすいです

**Comment by popmac** [comment]
ありがとうございます！
この観点について明確に説明しているものがなくて困ってました(> <)
resourcesメソッドじゃなくて自分でルーティングを追加する時に気をつけないといけなさそうな感じですね。
