### ISSUE TITLE
Rails5.1系でのGemのmysql2の適切なバージョン指定を知りたい

### ISSUE THREAD

**Issue by popmac** [camp17-extra/activities#32]
質問なんですが、Rails5.1系でMySQLを使うときって、
Gemの'mysql2'のバージョンってどういう風に指定するのが適切なんでしょうか？

GemのREADMEを見ると、0.4系じゃないと使えないみたいですが、
細かいバージョン指定はいくつにすればいいか分からなくて...

> mysql2 0.4.x works with Rails / Active Record 4.2.5 - 5.0 and higher.

https://github.com/brianmario/mysql2

**Comment by bake0937** [comment]
対応しているバージョンの中で新しいやつが良いんじゃないですか？

**Comment by KoichiOzaki** [comment]
そうすね。
バージョン間の不整合報告されてなければとりあえず最新の安定版入れればいいと思います！メジャーバージョンさへ抑えとけばあとはそんな考えないスタイルでいいんじゃないかなと！
あとマイナーバージョンの違いでmysql2どんだけ変わるのか知らないんですが、あんま違いないならちょっと古いやついれても別にいい気がします！

**Comment by popmac** [comment]
ありがとうございます！

某教材の動画でRails4.2.1の時にはmysql2のバージョンは安定版の0.3.18で指定するってあったので、Rails5.1系の時もそういうベストプラクティスがあるのかなと思っていました。

**Comment by popmac** [comment]
## 170719
- 以下の状況でHerokuにデプロイが出来ました！

### Gemfile

```
ruby '2.4.1'
gem 'rails', '~> 5.1.2'
gem 'mysql2', '>= 0.3.18', '< 0.5'
```

### Gemfile.lock

```
mysql2 (0.4.8)
rails (5.1.2)
RUBY VERSION
   ruby 2.4.1p111
```
